"""initial tables: assessment_records and audit_logs

Revision ID: 32b788f7dfe7
Revises: 
Create Date: 2026-03-03 21:30:18.105400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '32b788f7dfe7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('score_band', sa.String(length=20), nullable=False),
    sa.Column('barrier_severity', sa.String(length=10), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('request_payload', sqlite.JSON(), nullable=False),
    sa.Column('response_payload', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('detail', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('assessment_records')
    # ### end Alembic commands ###
